# Generated by Django 4.2.1 on 2023-05-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_yourorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='yourorder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='yourorder',
            name='date',
            field=models.DateField(verbose_name='Date you went'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
